### ISSUE TITLE
Pls. help with installing TSCU

### ISSUE THREAD

**Issue by balajikalluri** [hkayabilisim/TSCU#1]
Hello Dr.Huseyin Kaya,

Your TSCU utility looks to me a VERY good starting point for me to apply my dataset for time-series classification.

But I run into this problem of compiling your MEX files in the start-up, as you rightly mentioned in your manual. Below is the snapshot of my Matlab Window reporting the error during installation/compilation. I'm NOT a proficient user of Matlab, however I did a quick search on web to resolve this before I'm posting you for help. My search on web was vain.

Appreciate your quick help. !!!

Best,
Balaji 

![image](https://cloud.githubusercontent.com/assets/7898603/14771078/5aa5793c-0ab2-11e6-909d-e16f43965ace.png)

**Comment by hkayabilisim** [comment]
Dear Balaji,

I love MATLAB but sometimes setting up MEX is troublesome. You may have
install additional components or tweak some configurations. I've found a
very similar problem mentioned in the following URL.  You may try the
suggestions in the accepted answer section.

http://www.mathworks.com/matlabcentral/answers/95039-why-does-the-sdk-7-1-installation-fail-with-an-installation-failed-message-on-my-windows-system

Sincerely
Huseyin

**Comment by balajikalluri** [comment]
Dear Dr. Huseyin,

Yes ! Appreciate your quick support. I followed the steps described in the link and I managed to get MEX working. 

Now I look forward to playing with your utility and see how it fares. Had I encounter any issues or seek any further help regarding your tool, will ping you.

Thanks once again.

Best,
Balaji

**Comment by hkayabilisim** [comment]
Dear Balaji,

I'm glad, you made it! I suggest to follow this guideline:

http://timewarping.org/TSCU/doc/html/tscu_tutorial.html

**Comment by balajikalluri** [comment]
Dear Dr. Huseyin,

Yes. Indeed, I completely followed your steps in the tutorials page as it is using synthetic dataset from UCR repo and well results are pretty well reproduced (except for slightly variations at some places, which is OKAY). THUMBS UP :+1: for a good implementation.

BTW I'm now keen to apply similar procedure onto my dataset "OPLD". On that note, I would like to know, is it possible to use your implementations (either .m or .c files from your github page) as API in my code? Are there any such implementation someone has tried out before using TSCU? Am just curious...

Best,
Balaji

**Comment by hkayabilisim** [comment]
Dear Balaji,

I understand your concern. You want to "live" in your codes and yet make
calls to the TSCU whenever you need a signal alignment. Unfortunately, it
is not very suitable. I suggest preparing your dataset and feed them into
TSCU and test with the available routines in TSCU. If you are happy with
the results, I can give it a try to add some functionality into TSCU for
your request.

Huseyin

**Comment by balajikalluri** [comment]
Dear Dr. Huseyin,

Very nice of you. Appreciate your kind support. 

BTW I'd a good time playing with my data applying your easy to use utility. In general, the results that I've obtained through simple routines demonstrated by you in your tutorial implementing some of your TSCU routines looks reasonably good. However, to my surprise SVM with all the 3 alignment methods i.e. NONE, DTW, CDTW is performing poorer than KNN with the same 3 alignment methods. I don't really understand the reason why is it so ? To my intuition, both from the literature and the features/patterns present in my time-series dataset, SVM should be able to perform better than KNN. 

Anyway I would like to help me clarify why I receive such strange warnings/errors when I try to use different alignment methods (e.g. CTW, PTW) other than the rest. I understand from your manual and paper in Information Systems Journal (2015) that 6 different alignment approaches are implemented. An example snapshot of such error during execution is attached FYI
![image](https://cloud.githubusercontent.com/assets/7898603/14800823/27baf5e0-0b77-11e6-9347-5263160b1507.png)

Besides I would to suggest what would be another kool feature to make your utility even more powerful is to expand it to lot more SVM kernels and be able to identify the best choice of kernels through Cross-validation. I understand that the current implementation is limited to only linear & guassian.

Thanks in anticipation & look forward. 

Best,
KMB

**Comment by balajikalluri** [comment]
A different error while executing the same dataset with CTW alignment 
![image](https://cloud.githubusercontent.com/assets/7898603/14801057/1119ec90-0b79-11e6-8944-31f9946366a1.png)

**Comment by balajikalluri** [comment]
Another quick question to you...

Can we NOT tune the gaussian-SVM kernel for different gammas at the same-time call alignment=DTW or CDTW? When I try to do this my program gets stuck/hanged...any reasons??

For example, below is my code...

gammas=2.^(-5:5);
accuracies=zeros(1,numel(gammas));
for i=1:length(gammas)
    out=tscu(trn,tst,'Classifier','SVM','SVMKernel','gaussian','Alignment','DTW'...
        'SVMGamma',gammas(i),...
        'LogLevel','Alert');
    accuracies(i)=out.perf.OA;
end

FYI 
![image](https://cloud.githubusercontent.com/assets/7898603/14801793/b9613584-0b7e-11e6-9661-90436edb5dac.png)

Best,
KMB

**Comment by balajikalluri** [comment]
Sorry to throw at my too many questions...I just thought it would be appropriate to ask you as I keep playing with your tool, so that you can easily answer all of them in one-go. Thus it can avoid slack in response.

Appreciate your understanding Dr. Huysein.

Best,
KMB

**Comment by hkayabilisim** [comment]
I guess the reason of this error is the lack of compiled MEX file suitable
for your environment. I remember compiling dtwFord.m on my Mac OS. I guess
the file dtwFord.mexmaci64 comes from my compilation. You may compile the
dtwFord.m yourself on the same directory and try again. I hope that is the
reason.

[image: Inline image 1]

**Comment by balajikalluri** [comment]
Dear Dr.Huseyin,
Appreciate that support. I think there was something that went wrong with my appropriate listing of arguments in the execution of function - tscu(). I'd managed to successfully pull-off some preliminary analysis with my dataset now. Thanks for your support :+1: 
BTW may I know if there is a way we can do some sort of visualization of classification results either within the tool or using other libraries. For instance, beyond simple confusion matrix another layer of interpretation of classification e.g. KNN clustering or kernel plot showing the hyperplane and instance of classes, would be much more valuable as a complement to the results produced using TSCU. 
If you don't have time, may be I could do it quickly and can help integrate to your tool. Any quick and easy suggestions & ideas would be appreciable in this regard.

Best,
Balaji

**Comment by hkayabilisim** [comment]
Dear Balaji,

The visualization of the instances, hyperplanes, etc  is troublesome
because the instances in the classification are time series of let's say
length n. So the instances lie in R^n space. Laying down the instances on a
2D paper has major problems. This was a problem I had been facing many
times. I had come across some techniques but I couldn't progressed very
much.

Let me share share some of my bookmarks that I collected for this:

http://people.cs.vt.edu/~north/infoviz/starcoords.pdf
http://davis.wpi.edu/~xmdv/index.html
http://www.infovis-wiki.net/index.php?title=PRISMA_-_A_multidimensional_information_visualization_tool

I hope they can help you.

Sincerely
Huseyin

**Comment by balajikalluri** [comment]
Yes Dr.Huseyin. I agree. This is indeed CHALLENGING !
Anyway appreciate your continued support.

Best,
Balaji
