### ISSUE TITLE
Not working for large dataset

### ISSUE THREAD

**Issue by paul-ang** [hkayabilisim/TSCU#3]
Hi,

I get Requested 331274x82822 (204.4GB) array exceeds maximum array size preference in tscu>nnclassifier(line 486).

Thanks.
Best regards.

**Comment by hkayabilisim** [comment]
Hi,

I fixed the issue. I'll be glad if you confirm it works for you. You should switch to the new branch:  #4 . After you confirm it, I will merge it to the master.

**Comment by paul-ang** [comment]
Hi,

Ok, I am testing it now. Because my dataset is big (almost 300K tseries), it will take some time to test. I will let you know when I get the result. 

Thank You.

**Comment by hkayabilisim** [comment]
Have you completed the test yet?
