### ISSUE TITLE
Error using svmtrain

### ISSUE THREAD

**Issue by wwjd1234** [hkayabilisim/TSCU#7]
So I think matlab now uses an updated svm function to train, so I get this error when running the command "tscu(trn,tst,'Classifier','SVM');" :

Error using svmtrain (line 230)
svmtrain has been removed. Use fitcsvm instead.

Error in tscu>svmclassifier (line 677)
model = svmtrain(x(:,1),[(1:nx)',KernelTrain_vs_Train], svmopts);

Error in tscu (line 303)
        [labels,model] = svmclassifier(x,y,options);

**Comment by hkayabilisim** [comment]
I'm guessing you are using Microsoft Windows. Can you try copying Windows-compatible MEX files (already inside TSCU) to TSCU root folder, as follows? And run TSCU again.

$ pwd
/Users/hkaya/Dropbox/TSCU
$ cp ./src/lib/libsvm/windows/svmtrain.mexw64 .
$ cp ./src/lib/libsvm/windows/svmpredict.mexw64 .

**Comment by hkayabilisim** [comment]
svmtrain and svmtrain are prebuilt-MEX files of libsvm. In TSCU, there are Linux and Mac prebuilt-binaries but corresponding Windows binaries were in the wrong directory. I corrected it. Can you update your TSCU copy by git pull.
