### ISSUE TITLE
error compiling tscu_dtw.c

### ISSUE THREAD

**Issue by Yunansahara** [hkayabilisim/TSCU#8]
Hello Sir,
I am totally new at time series classification but I do interest on this subject field so I tried to run mex tscu_dtw.c as mentioned on your tscu_manual.pdf and an issue came up

>> mex tscu_dtw.c
Building with 'MinGW64 Compiler (C)'.
Error using med
E:\Matlab2017\bin\tscu_dtw.c: In function 'mexFunction':
E:\Matlab2017\bin\tscu_dtw.c: 144:21:
error: expected ';' before '}'
token
144 |          mexErrMsgTxt
        |                                  ^
        |                                  ;
145 |
146 |         } else if (nlhs  > 3 ) {
        |        ~

I do appreciate for the help 😊

**Comment by hkayabilisim** [comment]
Dear Yunansahara!

I couldn't figure out why you are getting this error. I'm assuming you just pulled the code and run "mex tscu_dtw.c" without changing anything. Am I correct?  

I wonder if your MEX environment is working correctly. Have you compiled another MEX file successfully on your environment?

**Comment by hkayabilisim** [comment]
Have you tried compiling any MEX file on your environment? I'm suspecting a
setup issue related to MEX.

**Comment by Yunansahara** [comment]
Yes Sir, i didn't change anything. I run mex -setup and I got msg that MinGW64 Compiler has been installed on my system. Did you mean compiling mex file on my environment related to that??

**Comment by Yunansahara** [comment]
Yes Sir, i didn't change anything. I run mex -setup and I got msg that MinGW64 Compiler has been installed on my system. Did you mean compiling mex file on my environment related to that??

**Comment by Yunansahara** [comment]
Hi sir, 

I didn't copy the source MEX file to a writeable folder on my path yet before. That's why such that error occurred. But now it fixed.
Thank you Sir
God Bless you

**Comment by hkayabilisim** [comment]
Thank you for closing the issue for me. If you have further questions, please feel free to ask!
